import type { OffPageOpportunity } from '@/types'

export const OFF_PAGE_OPPORTUNITIES: Omit<OffPageOpportunity, 'status'>[] = [
  // Local / Business directories
  {
    id: 'google-business',
    platform: 'Google Business Profile',
    domain: 'business.google.com',
    domainAuthority: 100,
    category: 'local',
    description: 'The most important local listing. Appears in Google Maps and local search results.',
    signupUrl: 'https://business.google.com',
    steps: [
      'Go to business.google.com and click "Manage now"',
      'Sign in with your Google account',
      'Enter your business name and category',
      'Add your address (or service area if you serve customers at their location)',
      'Add your phone number and website',
      'Choose a verification method (postcard, phone, or email)',
      'Once verified, complete your profile: add photos, hours, description, and services',
    ],
  },
  {
    id: 'bing-places',
    platform: 'Bing Places for Business',
    domain: 'bingplaces.com',
    domainAuthority: 93,
    category: 'local',
    description: 'Powers Bing search and Microsoft Copilot local results. Import from Google in one click.',
    signupUrl: 'https://www.bingplaces.com',
    steps: [
      'Go to bingplaces.com',
      'Click "Get started"',
      'Sign in with Microsoft account',
      'Import from Google Business Profile (easiest) OR enter business details manually',
      'Verify your listing via phone or postcard',
    ],
  },
  {
    id: 'apple-business-connect',
    platform: 'Apple Business Connect',
    domain: 'businessconnect.apple.com',
    domainAuthority: 95,
    category: 'local',
    description: 'Controls how your business appears in Apple Maps, Siri, and Apple Intelligence.',
    signupUrl: 'https://businessconnect.apple.com',
    steps: [
      'Go to businessconnect.apple.com',
      'Sign in with your Apple ID',
      'Search for your business or add a new one',
      'Claim and verify your listing',
      'Add photos, hours, and business details',
    ],
  },
  {
    id: 'yelp',
    platform: 'Yelp for Business',
    domain: 'biz.yelp.com',
    domainAuthority: 94,
    category: 'local',
    description: 'High DA directory essential for US service businesses. Heavily cited in AI answers.',
    signupUrl: 'https://biz.yelp.com',
    steps: [
      'Go to biz.yelp.com',
      'Search for your business or click "Add your business"',
      'Enter business name, address, and category',
      'Claim and verify the listing',
      'Add photos, business hours, and services',
      'Enable messaging so customers can contact you directly',
    ],
  },
  {
    id: 'bbb',
    platform: 'Better Business Bureau',
    domain: 'bbb.org',
    domainAuthority: 92,
    category: 'local',
    description: 'Trust signal for US businesses. Basic listing is free; accreditation is paid.',
    signupUrl: 'https://www.bbb.org/accreditation/apply',
    steps: [
      'Go to bbb.org and search for your business',
      'If not listed, click "Add Your Business"',
      'Fill in your business details (name, address, category, website)',
      'Submit for a free basic listing',
      'Respond promptly to any customer reviews that come in',
    ],
  },
  {
    id: 'trustpilot',
    platform: 'Trustpilot',
    domain: 'trustpilot.com',
    domainAuthority: 92,
    category: 'local',
    description: 'Free profile with Review schema support. Reviews appear in Google search results.',
    signupUrl: 'https://business.trustpilot.com/signup',
    steps: [
      'Go to business.trustpilot.com/signup',
      'Create a free business account',
      'Claim your business profile',
      'Add your website URL and business details',
      'Invite existing customers to leave reviews',
      'Respond to all reviews (positive and negative)',
    ],
  },
  // Social / Web 2.0
  {
    id: 'linkedin-company',
    platform: 'LinkedIn Company Page',
    domain: 'linkedin.com',
    domainAuthority: 98,
    category: 'social',
    description: 'Essential company page with website link. Very high DA, indexed quickly.',
    signupUrl: 'https://www.linkedin.com/company/setup/new',
    steps: [
      'Sign in to LinkedIn with your personal account',
      'Go to linkedin.com/company/setup/new',
      'Enter your company name, website, and industry',
      'Add a company logo and cover image',
      'Write a compelling "About" section with your keywords',
      'Add your website URL in the company details',
      'Share your first post to activate the page',
    ],
  },
  {
    id: 'medium',
    platform: 'Medium',
    domain: 'medium.com',
    domainAuthority: 95,
    category: 'social',
    description: 'Republish blog posts with canonical link back to your site. Strong for content marketing.',
    signupUrl: 'https://medium.com/m/signin',
    steps: [
      'Create a Medium account at medium.com',
      'Go to your profile settings and add your website URL',
      'For each blog post you want to syndicate: click "Import story"',
      'Enter your original post URL — Medium will import it automatically',
      'Medium sets a canonical link back to your site (protects SEO)',
      'Publish and add relevant tags to reach Medium\'s audience',
    ],
  },
  {
    id: 'pinterest-business',
    platform: 'Pinterest Business',
    domain: 'pinterest.com',
    domainAuthority: 94,
    category: 'social',
    description: 'Claim your website to enable rich pins and get traffic from visual search.',
    signupUrl: 'https://business.pinterest.com',
    steps: [
      'Create or convert to a Pinterest business account',
      'Go to Settings → Claim → enter your website URL',
      'Add the meta tag or upload the HTML file Pinterest provides',
      'Click "Submit" — Pinterest will verify your site',
      'Once claimed, your profile picture appears on all pins from your site',
      'Create boards relevant to your niche and pin your content',
    ],
  },
  {
    id: 'crunchbase',
    platform: 'Crunchbase',
    domain: 'crunchbase.com',
    domainAuthority: 92,
    category: 'directory',
    description: 'Company profile with website field. Heavily used by AI systems as a data source.',
    signupUrl: 'https://www.crunchbase.com/add-organization',
    steps: [
      'Go to crunchbase.com and create an account',
      'Navigate to add-organization',
      'Enter company name, website, and description',
      'Add funding information, team members, and social links',
      'Verify your email and complete the profile',
    ],
  },
  {
    id: 'product-hunt',
    platform: 'Product Hunt',
    domain: 'producthunt.com',
    domainAuthority: 91,
    category: 'directory',
    description: 'Launch your product for visibility, backlinks, and potential viral traffic spike.',
    signupUrl: 'https://www.producthunt.com/posts/new',
    steps: [
      'Create a Product Hunt account',
      'Click "Submit" to add your product',
      'Add product name, tagline, website, and description',
      'Upload screenshots or a demo video',
      'Choose the right category for your product',
      'Schedule launch for Tuesday/Wednesday for maximum upvotes',
      'Engage with comments on launch day',
    ],
  },
  {
    id: 'quora',
    platform: 'Quora',
    domain: 'quora.com',
    domainAuthority: 93,
    category: 'social',
    description: 'Answer questions in your niche. Links in answers drive targeted referral traffic.',
    signupUrl: 'https://www.quora.com',
    steps: [
      'Create a Quora account and complete your profile',
      'Add your website URL to your profile bio',
      'Search for questions related to your niche',
      'Write comprehensive, helpful answers (no spammy links)',
      'Add a relevant link to your site only where it genuinely helps the reader',
      'Follow topics in your niche to get question suggestions',
    ],
  },
]

export function getOffPageFindings(siteUrl: string) {
  return OFF_PAGE_OPPORTUNITIES.map(op => ({ ...op, status: 'todo' as const }))
}
